hmrc/manage-vat-subscription-frontend

app/views/govuk_wrapper.scala.html

BTAT-560 Added alpha banner to govuk-wrapper

---

app/config/ServiceErrorHandler.scala
app/controllers/CustomerDetailsController.scala
app/controllers/predicates/AuthenticationPredicate.scala
conf/app.routes
test/controllers/CustomerDetailsControllerSpec.scala
test/controllers/HelloWorldControllerSpec.scala
test/controllers/predicates/AuthenticationPredicateSpec.scala
test/mocks/MockAuth.scala
test/mocks/services/MockCustomerDetailsService.scala
test/utils/MaterializerSupport.scala
test/utils/TestUtil.scala

[BTAT-2546] Added CustomerDetailsController to render CustommerDetails view

---

app/config/ConfigKeys.scala
app/config/ServiceErrorHandler.scala
app/config/frontendAppConfig.scala
app/connectors/CustomerDetailsConnector.scala
app/controllers/ChangeBusinessNameController.scala
app/controllers/CustomerDetailsController.scala
app/controllers/predicates/AuthenticationPredicate.scala
app/services/CustomerDetailsService.scala
app/views/businessName/change_business_name.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/assets/messages/BaseMessages.scala
test/assets/messages/ChangeBusinessNamePageMessages.scala
test/controllers/ChangeBusinessNameControllerSpec.scala
test/controllers/CustomerDetailsControllerSpec.scala
test/controllers/HelloWorldControllerSpec.scala
test/controllers/predicates/AuthenticationPredicateSpec.scala
test/mocks/MockAppConfig.scala
test/mocks/MockAuth.scala
test/mocks/connectors/MockCustomerDetailsConnector.scala
test/mocks/services/MockCustomerDetailsService.scala
test/services/CustomerDetailsServiceSpec.scala
test/utils/MaterializerSupport.scala
test/utils/TestUtil.scala
test/views/businessName/ChangeBusinessNameViewSpec.scala

[BTAT-2550] Added ChangeBusinessNameController

---

conf/app.routes
test/controllers/returnFrequency/ConfirmVatDatesControllerSpec.scala
test/views/returnFrequency/ConfirmDatesViewSpec.scala

-Change the business details page
-Choose new Vat return dates
-Confirm new Vat return dates
-Confirmation page Vat return dates
-Agent

Changed URLs for

---

app/views/businessName/change_business_name.scala.html
conf/messages
test/assets/messages/ChangeBusinessNamePageMessages.scala
test/views/businessName/ChangeBusinessNameViewSpec.scala

Acceptance Test PR:
https://github.com/hmrc/change-vat-acceptance-tests/pull/15

[BTAT-2791] Iterated the content for change business name to v0.3.0 of proto

---

app/views/customerInfo/customer_details.scala.html
conf/messages
test/assets/messages/CustomerDetailsPageMessages.scala
test/views/customerInfo/CustomerDetailsViewSpec.scala

AT PR:
https://github.com/hmrc/change-vat-acceptance-tests/pull/16

[BTAT-2792] Updated 'change business details' home page to match v0.3.0 of proto

---

app/views/businessAddress/change_address_confirmation.scala.html
conf/messages
test/assets/messages/BaseMessages.scala
test/assets/messages/ChangeAddressConfirmationPageMessages.scala
test/views/ViewBaseSpec.scala
test/views/businessAddress/ChangeAddressConfirmationViewSpec.scala

AT PR:
https://github.com/hmrc/change-vat-acceptance-tests/pull/17

[BTAT-2793] Uupdated business address confirmation to v0.3.0 of proto

---

app/testOnly/views/featureSwitch.scala.html
app/views/agentClientRelationship/confirm_client_vrn.scala.html
app/views/agentClientRelationship/select_client_vrn.scala.html
app/views/businessAddress/change_address_confirmation.scala.html
app/views/businessName/change_business_name.scala.html
app/views/customerInfo/customer_circumstance_details.scala.html
app/views/errors/agent/notAuthorisedForClient.scala.html
app/views/errors/agent/unauthorised.scala.html
app/views/errors/sessionTimeout.scala.html
app/views/errors/unauthorised.scala.html
app/views/helpers/render_address.scala.html
app/views/helpers/render_return_frequency.scala.html
app/views/returnFrequency/change_return_frequency_confirmation.scala.html
app/views/returnFrequency/chooseDates.scala.html
app/views/returnFrequency/confirm_dates.scala.html
app/views/templates/errors/errorSummary.scala.html
app/views/templates/headings.scala.html
app/views/templates/inputs/checkboxList.scala.html
app/views/templates/inputs/date.scala.html
app/views/templates/inputs/dateEntryField.scala.html
app/views/templates/inputs/money.scala.html
app/views/templates/inputs/radioGroup.scala.html
app/views/templates/inputs/singleCheckbox.scala.html
app/views/templates/inputs/text.scala.html
build.sbt
conf/application.conf
project/plugins.sbt

**Note**
Bump in libraries has caused all package headers to be indented by 1 space. 🍺

[BTAT-2950] Update dependencies to latest version. inc. assets frontend

---

app/config/FrontendAppConfig.scala
conf/application.conf

App-Config-Base needs reviewing first.
https://github.com/hmrc/app-config-base/pull/302
To ensure that the base config is baked into the build.

[change-config] Minor refactor for agent services authorise url

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/SignOutController.scala
app/views/errors/sessionTimeout.scala.html
app/views/govuk_wrapper.scala.html
app/views/main_template.scala.html
conf/app.routes
conf/application.conf
test/controllers/SignOutControllerSpec.scala
test/mocks/MockAppConfig.scala

To test locally; update `application.conf` and change the timeout period and countdown.

[BTAT-3158] Added timeout to support accessible users

---

app/views/customerInfo/customer_circumstance_details.scala.html
app/views/returnFrequency/chooseDates.scala.html

To prove - select Wave from the toolbar on these pages and (non GOV template) warnings have been removed

Accessibility fixes

---

app/models/customerAddress/AddressLookupJsonBuilder.scala
app/views/errors/not_signed_up.scala.html
app/views/returnFrequency/chooseDates.scala.html
app/views/templates/breadcrumb.scala.html
app/views/templates/inputs/radioGroup.scala.html
conf/messages
test/assets/CustomerAddressTestConstants.scala
test/assets/messages/AddressLookupMessages.scala
test/assets/messages/ClientVrnPageMessages.scala
test/assets/messages/ConfirmClientVrnPageMessages.scala
test/assets/messages/ReturnFrequencyMessages.scala
test/controllers/returnFrequency/ChangeReturnFrequencyConfirmationSpec.scala
test/controllers/returnFrequency/ChooseDatesControllerSpec.scala
test/controllers/returnFrequency/ConfirmVatDatesControllerSpec.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala
test/views/returnFrequency/ChooseDatesViewSpec.scala
test/views/returnFrequency/ConfirmDatesViewSpec.scala
test/views/templates/inputs/RadioGroupTemplateSpec.scala

Addresses the following:
- Page 16 - Page title not unique on all pages
- Page 20 & 21 - 'Choose the new VAT Return dates' page - restructured legend and additional help text

Made DAC recommended changes

---

app/controllers/CustomerCircumstanceDetailsController.scala
test/controllers/CustomerCircumstanceDetailsControllerSpec.scala

Deleted session data upon hitting the 'change of business details' page (not user data).
Ran the tests
Ran AT against the branch

BTAT- 3338

---

app/config/FrontendAppConfig.scala
app/config/VatcHeaderCarrierForPartialsConverter.scala
app/controllers/feedback/FeedbackController.scala
app/views/feedback/feedback.scala.html
app/views/feedback/feedback_thankyou.scala.html
app/views/govuk_wrapper.scala.html
conf/app.routes
conf/messages
test/mocks/MockAppConfig.scala

Service-Manager-Config PR:
https://github.com/hmrc/service-manager-config/pull/313

[BTAT-3265] Added the feedback survey partial

---

app/config/FrontendAppConfig.scala
app/controllers/feedback/FeedbackController.scala
conf/application.conf
test/mocks/MockAppConfig.scala

app-config-base PR: https://github.com/hmrc/app-config-base/pull/389

[BTAT-3341] Use contact-frontend host for feedback URL

---

app/models/customerAddress/AddressModel.scala
app/models/updatePPOB/UpdatePPOBAddress.scala
app/services/PPOBService.scala
it/pages/BusinessAddressControllerISpec.scala
test/assets/CustomerAddressTestConstants.scala
test/assets/UpdatePPOBAddressTestConstants.scala
test/audit/models/ChangeAddressAuditModelSpec.scala
test/controllers/BusinessAddressControllerSpec.scala
test/mocks/services/MockBusinessAddressService.scala
test/services/PPOBServiceSpec.scala

Associated backend PR:
https://github.com/hmrc/vat-subscription/pull/124

[BTAT-3522] Mandatory countryCode, match latest DES Schema requirements

---

app/controllers/BusinessAddressController.scala
app/views/customerInfo/customer_circumstance_details.scala.html
conf/app.routes
it/pages/BusinessAddressControllerISpec.scala
test/controllers/BusinessAddressControllerSpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

Reverts hmrc/manage-vat-subscription-frontend#178

Revert "[BTAT-3443] - added isAgent queryParam to ppob change"

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/errors/not_signed_up.scala.html
conf/application.conf
conf/messages
test/assets/messages/NotSignedUpPageMessages.scala
test/mocks/MockAppConfig.scala
test/views/errors/NotSignedUpViewSpec.scala

https://github.com/hmrc/change-vat-acceptance-tests/pull/101

[BTAT-4257] updated content for not signed up error page

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/models/circumstanceInfo/CircumstanceDetails.scala
app/services/CustomerCircumstanceDetailsService.scala
app/views/customerInfo/customer_circumstance_details.scala.html
conf/application.conf
it/helpers/IntegrationTestConstants.scala
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
test/assets/CircumstanceDetailsTestConstants.scala
test/mocks/MockAppConfig.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[BTAT-4255] updated customer details page to only show business name with specific party types

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Feature.scala
app/config/features/Features.scala
app/controllers/agentClientRelationship/ConfirmClientVrnController.scala
app/controllers/predicates/AuthoriseAsAgentWithClient.scala
app/testOnly/TestOnlyAppConfig.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/forms/StubAgentClientLookupForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/models/StubAgentClientLookupModel.scala
app/testOnly/views/featureSwitch.scala.html
app/testOnly/views/stubAgentClientLookup.scala.html
app/testOnly/views/stubAgentClientUnauth.scala.html
conf/app.routes
conf/application.conf
conf/prod.routes
conf/testOnlyDoNotUseInAppConf.routes
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
it/pages/agentClientRelationship/ConfirmClientVrnControllerISpec.scala
it/pages/returnFrequency/ChangeReturnFrequencyConfirmationISpec.scala
test/config/WhitelistFilterSpec.scala
test/config/features/FeatureSpec.scala
test/controllers/agentClientRelationship/ConfirmClientVrnControllerSpec.scala
test/controllers/predicates/AuthoriseAsAgentWithClientSpec.scala
test/mocks/MockAppConfig.scala
test/utils/TestUtil.scala
test/views/templates/inputs/SingleCheckboxTemplateSpec.scala

**App Configs**
https://github.com/hmrc/app-config-base/pull/1200
https://github.com/hmrc/app-config-qa/pull/2529
https://github.com/hmrc/app-config-staging/pull/1609
https://github.com/hmrc/app-config-production/pull/2087
**Acceptance Tests PR**
https://github.com/hmrc/change-vat-acceptance-tests/pull/108

[BTAT-4338] Added handoff to VACLF with feature switch and stubbed endpoints for testing

---

app/controllers/BusinessAddressController.scala
app/views/businessAddress/change_address.scala.html
app/views/customerInfo/customer_circumstance_details.scala.html
conf/app.routes
conf/messages
it/pages/BusinessAddressControllerISpec.scala
test/assets/messages/ChangeAddressPageMessages.scala
test/controllers/BusinessAddressControllerSpec.scala
test/views/businessAddress/ChangeAddressViewSpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

https://github.com/hmrc/change-vat-acceptance-tests/pull/111

[BTAT-4376]: added change address page

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Features.scala
app/models/customerAddress/AddressLookupOnRampModel.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/controllers/StubAddressLookupController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/models/StubAddressLookupJourneyConfig.scala
app/testOnly/views/featureSwitch.scala.html
app/testOnly/views/stubAddressLookup.scala.html
conf/application.conf
conf/testOnlyDoNotUseInAppConf.routes
it/pages/BusinessAddressControllerISpec.scala

https://github.com/hmrc/change-vat-acceptance-tests/pull/113

[BTAT 4425] added address lookup feature switch and stub

---

app/controllers/agentClientRelationship/ConfirmClientVrnController.scala
app/controllers/predicates/AuthPredicate.scala
app/controllers/predicates/AuthoriseAsAgentWithClient.scala

Also removed WARN level logs where they are not useful

Added logging for authorised agent for client but 404 DES response

---

app/views/customerInfo/customer_circumstance_details.scala.html
conf/messages
conf/messages.cy
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

Please review but do not merge until we have sign off for the Welsh screenshots.

Updated chocs overview page title, removed subheading and added Welsh

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/customerInfo/customer_circumstance_details.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

Ensure these are merged first please:
• https://github.com/hmrc/app-config-base/pull/2498
• https://github.com/hmrc/app-config-production/pull/4390

BTAT-6617 Renamed and reused MTD section feature for phone/website ChoC

---

conf/messages
conf/messages.cy
it/assets/BaseITConstants.scala
test/assets/BaseTestConstants.scala
test/assets/messages/AddressLookupMessages.scala
test/assets/messages/BaseMessages.scala
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/controllers/predicates/InflightEmailPredicateSpec.scala

Please review the AT's as part of this merge: https://github.com/hmrc/change-vat-acceptance-tests/pull/152

BTAT-6635 Updated nav title for agent journey

---

app/views/returnFrequency/chooseDates.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ReturnFrequencyMessages.scala
test/controllers/returnFrequency/ChooseDatesControllerSpec.scala
test/views/returnFrequency/ChooseDatesViewSpec.scala

task BTAT-6806 also changes the messages files to one will need to rebased

BTAT 6803 added error prefix if the form has errors 

---

app/models/returnFrequency/ReturnPeriod.scala
build.sbt
conf/messages
conf/messages.cy
test/assets/ReturnPeriodTestConstants.scala
test/assets/messages/ReturnFrequencyMessages.scala
test/models/returnFrequency/ReturnPeriodSpec.scala
test/views/helpers/RenderReturnFrequencySpec.scala

[DM] [BTAT-6944] Added Annually to ReturnPeriod reads

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
build.sbt
conf/application.conf
conf/messages
conf/messages.cy
test/config/features/FeaturesSpec.scala
test/utils/TestUtil.scala

BTAT-6966 Removed simple auth

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/govuk_wrapper.scala.html
conf/application.conf
test/views/GovUkWrapperSpec.scala

BTAT-7033 Remove ally report link

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/customerInfo/customer_circumstance_details.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/utils/TestUtil.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-6969 - Removed contactDetailsSection feature switch

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/connectors/AddressLookupConnector.scala
app/models/customerAddress/AddressLookupJsonBuilder.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf
it/pages/BusinessAddressControllerISpec.scala
test/connectors/AddressLookupConnectorSpec.scala
test/models/customerAddress/AddressLookupJsonBuilderSpec.scala
test/utils/TestUtil.scala

* [ x] Branch is rebased with master
* [ x] Added Unit Tests for changed functionality
* [ x] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ x] Ran Acceptance tests as per the story. If any query ping in group slack and confirm the AT's repo
* [x ] (If applicable) raised app-config-* PRs

BTAT-7032 - Removed useNewAddressLookupFeature switch

---

app/models/customerAddress/AddressLookupJsonBuilder.scala

Removed unused Version 1

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
app/views/businessAddress/change_address_confirmation.scala.html
app/views/customerInfo/customer_circumstance_details.scala.html
app/views/returnFrequency/change_return_frequency_confirmation.scala.html
conf/application.conf
conf/messages
test/views/businessAddress/ChangeAddressConfirmationViewSpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala
test/views/returnFrequency/ChangeReturnFrequencyConfirmationViewSpec.scala

BTAT-7031 deleted featureSwitch changeClient

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/featureSwitch.scala.html
conf/application.conf

Please ensure the following PR is merged too: https://github.com/hmrc/app-config-production/pull/4809

BTAT-7047 Added feature switch for mtd sign up

---

app/models/circumstanceInfo/CircumstanceDetails.scala
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
test/assets/CircumstanceDetailsTestConstants.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-7121 Corrected logic for pending removal of contact details

---

app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/VatSubscriptionFeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html

StubDesRemoved

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
conf/application.conf

Added separate host for calling bta as microservice connector

---

app/views/GovukWrapper.scala.html
public/css/palette.css

ensured language toggle comes first

---

app/views/errors/ChangePendingView.scala.html
conf/messages
conf/messages.cy
project/plugins.sbt
test/assets/messages/ChangePendingMessages.scala
test/views/errors/ChangePendingViewSpec.scala

BTAT-7302 Iterated inflight change error page

---

conf/messages.cy
project/plugins.sbt

BTAT-7336 Updaing inflight welsh content

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/config/features/FeaturesSpec.scala
test/utils/TestUtil.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-7314 Removed useVatReturn Feature Switch

---

app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
project/plugins.sbt

* [y ] Branch is rebased with master
* [ y] Added Unit Tests for changed functionality
* [ y] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [y ] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [ y] Ran Acceptance tests as per the story. If any query ping in group slack and confirm the AT's repo

BTAT-7174 moved website into business detail section

---

conf/application.conf
conf/messages
conf/messages.cy
test/views/errors/SessionTimeoutViewSpec.scala

BTAT-7415: Added xss protection and removed dumb punctuation

---

app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/messages
conf/messages.cy
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-7023 Moving return frequency to own section on ChoCs

---

build.sbt
project/build.properties
project/plugins.sbt

Minor dependency updates

---

app/views/templates/Breadcrumb.scala.html
conf/messages
conf/messages.cy
test/assets/messages/BaseMessages.scala

BTAT-7537 - Fixed breadcrumb text

---

app/utils/ImplicitDateFormatter.scala

Updated currentDate to be a def for re-evaluation purposes

---

app/views/GovukWrapper.scala.html
public/css/palette.css

* [n/a ] Added Unit Tests for changed functionality

BTAT-7612 Move BTA links above language toggle

---

app/views/GovukWrapper.scala.html
public/css/vat-v1.0.css
public/javascript/vat-v1.0.js

[DM] [BTAT-7762] Improved rendering on Internet Explorer

---

app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/VatSubscriptionFeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html

BTAT-7751 Added support for new backend feature switch

---

app/models/customerAddress/AddressLookupJsonBuilder.scala
conf/messages
conf/messages.cy
test/assets/CustomerAddressTestConstants.scala
test/assets/messages/AddressLookupMessages.scala

This reverts commit cbec6151b10264e9118f499df300153dde3835ad.

Revert "Work in Progress"

---

app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/Api1363Version.scala
app/testOnly/models/Api1365Version.scala
app/testOnly/views/FeatureSwitchView.scala.html
build.sbt
project/plugins.sbt

Please ensure the other tasks in the story are also merged alongside this one

BTAT-7845 Updated API version identifiers for backend feature switches

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf

TO BE MERGED AFTER https://github.com/hmrc/app-config-production/pull/7168

BTAT-7885 - Added feature switch for missing trader address

---

app/views/MissingTraderAddressConfirmationView.scala.html
conf/messages
project/plugins.sbt
test/assets/assets/messages/MissingTraderAddressConfirmationPageMessages.scala
test/mocks/MockAppConfig.scala
test/views/MissingTraderAddressConfirmationViewSpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

Wrote new view and spec

---

app/audit/models/MissingTraderAuditModel.scala
app/controllers/missingTrader/ConfirmAddressController.scala
build.sbt
project/plugins.sbt
test/audit/mocks/MockAuditingService.scala
test/controllers/BusinessAddressControllerSpec.scala
test/controllers/missingTrader/ConfirmAddressControllerSpec.scala

BTAT-7924 Added audit event for missing trader page

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf

TO BE MERGED FIRST - https://github.com/hmrc/app-config-production/pull/7318

BTAT-7960 - Added feature switch for contact details moving to BTA

---

conf/messages.cy

BTAT-7944 Adding welsh translation for missing tader pages

---

app/views/missingTrader/ConfirmBusinessAddressView.scala.html
conf/messages
conf/messages.cy
public/css/vat-v1.0.css
test/assets/messages/ConfirmBusinessAddressMessages.scala
test/views/missingTrader/ConfirmBusinessAddressViewSpec.scala

BTAT-7994 Adding additional content for missing trader screen

---

app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-7995 - dont show email nudge if pendingEmail

---

conf/messages.cy

BTAT-8045 Updating welsh content for BTA account detail section on ChOCs

---

app/controllers/predicates/InFlightPPOBPredicate.scala
app/views/errors/ChangePendingView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ChangePendingMessages.scala
test/controllers/predicates/InFlightPPOBPredicateSpec.scala
test/views/errors/ChangePendingViewSpec.scala

BTAT-8077-2 - Updated inflight PPOB change content and predicate

---

conf/application.conf

BTAT-8118 - Updated assets frontend to 3.11.0

---

build.sbt

* [] Ran Acceptance tests as per the story. If any query ping in group slack and confirm the AT's repo
* [] Ran Performance tests as per the story. If any query ping in group slack and confirm the PT's repo

updated to avoid unstable build

---

app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-8272 Replaced hardcoded hidden text with i18n message

---

build.sbt
it/helpers/SessionCookieBaker.scala
project/build.properties
project/plugins.sbt

BTAT-8311 Removed usages of uk.gov.hmrc.http.SessionKeys

---

app/views/GovukWrapper.scala.html
app/views/missingTrader/ConfirmBusinessAddressView.scala.html
app/views/templates/errors/ErrorSummary.scala.html
app/views/templates/inputs/RadioGroup.scala.html
app/views/templates/inputs/Text.scala.html
conf/messages
conf/messages.cy
test/views/missingTrader/ConfirmBusinessAddressViewSpec.scala
test/views/templates/errors/ErrorSummarySpec.scala
test/views/templates/inputs/ErrorSummarySpec.scala
test/views/templates/inputs/RadioGroupTemplateSpec.scala
test/views/templates/inputs/TextTemplateSpec.scala

BTAT- 8321

---

app/models/customerAddress/AddressLookupJsonBuilder.scala

BTAT-8407 add accessibility statement in address-lookup-frontend

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/GovukWrapper.scala.html
app/views/MainTemplate.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
run.sh
test/mocks/MockAppConfig.scala

[BTAT-8425] Added GTM snippet for tracking consent banner

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
build.sbt
conf/application.conf

Please ensure this is merged too:
- https://github.com/hmrc/app-config-production/pull/8567

BTAT-8489 Add feature switch for trading name

---

app/config/FrontendAppConfig.scala
conf/application.conf

BTAT-8650 updating sign out URL's for BAS_GATEWAY routes

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf

BTAT-8715 feature switch for organisationNameR19

---

test/controllers/ChangeBusinessNameControllerSpec.scala

Updating tests for users who see the COHO change business name page

---

app/models/circumstanceInfo/CustomerDetails.scala
app/views/errors/NotSignedUpView.scala.html
it/helpers/IntegrationTestConstants.scala
test/assets/CustomerDetailsTestConstants.scala
test/models/circumstanceInfo/CustomerDetailsSpec.scala
test/views/errors/NotSignedUpViewSpec.scala

[BTAT-8944] - updated insolvency check to account for insolvency types

---

app/testOnly/views/FeatureSwitchView.scala.html
app/views/helpers/RenderAddress.scala.html
app/views/missingTrader/ConfirmBusinessAddressView.scala.html
app/views/templates/inputs/RadioGroup.scala.html
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala
test/views/helpers/RenderAddressSpec.scala
test/views/missingTrader/ConfirmBusinessAddressViewSpec.scala
test/views/templates/inputs/RadioGroupTemplateSpec.scala

BTAT-8988 HTML restructure to Missing Trader view and RadioGroup template

---

app/models/circumstanceInfo/CircumstanceDetails.scala
app/models/circumstanceInfo/PendingChanges.scala
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/messages
it/helpers/IntegrationTestConstants.scala
test/assets/CircumstanceDetailsTestConstants.scala
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[BTAT-9024] Set business name status to pending until approved

---

app/views/GovukWrapper.scala.html
build.sbt
public/css/vat-v1.1.css

BTAT-9006 Added CSS to fix menu toggle disppearance issue for small screens

---

build.sbt
conf/messages.cy

I removed play-language from the dependencies because it didn't seem like we were using it and the readme says we shouldn't be using anyway if we're using play-frontend-hmrc

 [BTAT-9190] Added missing Welsh messages for change business name journey

---

app/controllers/BusinessAddressController.scala
build.sbt
test/controllers/BusinessAddressControllerSpec.scala

[BTAT-9279] Added inflight predicate to .callback action to avoid 409s

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
conf/application.conf

Fix query param issue with address-lookup-frontend handoff

---

app/views/MainTemplate.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html

[BTAT-9387] Removed breadcrumbs from Main landmark

---

app/views/MainTemplate.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html

Reverts hmrc/manage-vat-subscription-frontend#431

Revert "[BTAT-9387] Removed breadcrumbs from Main landmark"

---

app/views/MainTemplate.scala.html
app/views/businessAddress/ChangeAddressView.scala.html
app/views/businessName/AltChangeBusinessNameView.scala.html
app/views/businessName/ChangeBusinessNameView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt

Btat 9387 a Created new branch to re-open PR

---

app/assets/stylesheets/application.scss
app/views/MainTemplate.scala.html
app/views/missingTrader/ConfirmBusinessAddressView.scala.html
build.sbt

BTAT-9430 - Updated to HMRC Standard header

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
build.sbt
conf/application.conf
project/plugins.sbt

Btat 9511 Added feature switch for Overseas Change of PPOB

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/application.conf
test/utils/TestUtil.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[BTAT-9517] Removed showContactNumbersAndWebsite feature switch

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf
test/utils/TestUtil.scala

[BTAT-9518] Removed useLanguageSelector feature switch

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/BusinessAddressController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf
test/controllers/BusinessAddressControllerSpec.scala

BTAT-9521 Removed emailVerifiedFeature

---

app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[BTAT-9514] Show change link to overseas businesses

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
app/views/businessAddress/ChangeAddressConfirmationView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/ChangeAddressConfirmationPageMessages.scala
test/utils/TestUtil.scala
test/views/businessAddress/ChangeAddressConfirmationViewSpec.scala

BTAT-9522 Removed disableBulkPaper feature switch

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf
test/views/businessAddress/ChangeAddressConfirmationViewSpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

BTAT-9520 Removing changeClient feature switch config

---

app/models/customerAddress/AddressLookupJsonBuilder.scala
conf/messages
conf/messages.cy
test/assets/CustomerAddressTestConstants.scala
test/assets/messages/AddressLookupMessages.scala
test/models/customerAddress/AddressLookupJsonBuilderSpec.scala
test/utils/TestUtil.scala

BTAT-9556 update ALF json builder

---

app/assets/stylesheets/application.scss
app/views/MainTemplate.scala.html
app/views/utils/ServiceNameUtil.scala
test/views/MainTemplateSpec.scala
test/views/utils/ServiceNameUtilSpec.scala

BTAT-9595 Added dynamic service URL to header

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/controllers/missingTrader/ConfirmAddressController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/controllers/missingTrader/ConfirmAddressControllerSpec.scala

BTAT-9623 Removing redundant missing trader feature switch

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf

[BTAT-9622]-Removal of stub contact preferences feature

---

app/config/ConfigKeys.scala
app/config/features/Features.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt
conf/application.conf
project/plugins.sbt
test/utils/TestUtil.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

Btat 9626 Removed tradingNameRowR19.enabled feature switch

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Features.scala
app/controllers/ChangeBusinessNameController.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
conf/application.conf
test/controllers/ChangeBusinessNameControllerSpec.scala

BTAT-9627 Removing organisationNameRow19 feature

---

build.sbt

[BTAT-9648] Removed play-frontend-govuk

---

app/views/errors/NotSignedUpView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/NotSignedUpPageMessages.scala

[BTAT-9818] Updated link text on client unauthorised error page

---

app/config/FrontendAppConfig.scala
app/controllers/BusinessAddressController.scala
app/controllers/ChangeBusinessNameController.scala
app/controllers/CustomerCircumstanceDetailsController.scala
app/controllers/LanguageController.scala
app/controllers/predicates/AuthoriseAsAgentOnly.scala
app/controllers/predicates/InFlightRepaymentBankAccountPredicate.scala
app/models/User.scala
app/services/PaymentsService.scala
app/views/businessAddress/ChangeAddressConfirmationView.scala.html
app/views/errors/PPOBAddressFailureView.scala.html
app/views/helpers/BackToBusinessDetails.scala.html
build.sbt
conf/app.routes
it/pages/BusinessAddressControllerISpec.scala
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
test/assets/PaymentsTestConstants.scala
test/controllers/BusinessAddressControllerSpec.scala
test/controllers/ChangeBusinessNameControllerSpec.scala
test/controllers/CustomerCircumstanceDetailsControllerSpec.scala
test/controllers/LanguageControllerSpec.scala
test/controllers/PaymentsControllerSpec.scala
test/controllers/predicates/InFlightRepaymentBankAccountPredicateSpec.scala
test/views/businessAddress/ChangeAddressConfirmationViewSpec.scala
test/views/businessAddress/ChangeAddressViewSpec.scala
test/views/businessName/AltChangeBusinessNameViewSpec.scala
test/views/businessName/ChangeBusinessNameViewSpec.scala
test/views/errors/PPOBAddressFailureViewSpec.scala

BTAT-9839 Removed user type suffix from URLs

---

app/views/templates/BTALinks.scala.html

[BTAT-9937]-Removed id from bta nav links

---

app/common/SessionKeys.scala
app/controllers/BusinessAddressController.scala
app/controllers/CustomerCircumstanceDetailsController.scala
app/controllers/agentClientRelationship/ConfirmClientVrnController.scala
app/controllers/predicates/AuthoriseAsAgentWithClient.scala
app/services/PPOBService.scala
app/services/ReturnFrequencyService.scala
app/testOnly/controllers/StubAgentClientLookupController.scala
it/pages/BasePageISpec.scala
it/pages/BusinessAddressControllerISpec.scala
test/controllers/CustomerCircumstanceDetailsControllerSpec.scala
test/controllers/agentClientRelationship/ConfirmClientVrnControllerSpec.scala
test/utils/TestUtil.scala

[BTAT-9911] Renamed session keys

---

app/controllers/LanguageController.scala
build.sbt
project/plugins.sbt
test/controllers/BusinessAddressControllerSpec.scala
test/controllers/ChangeBusinessNameControllerSpec.scala
test/controllers/PaymentsControllerSpec.scala
test/controllers/missingTrader/ConfirmAddressControllerSpec.scala
test/mocks/services/MockCustomerCircumstanceDetailsService.scala

BTAT-9963 Patched gaps in test coverage for controllers

---

app/models/YesNo.scala
test/assets/BaseTestConstants.scala
test/assets/CircumstanceDetailsTestConstants.scala
test/assets/CustomerAddressTestConstants.scala
test/assets/CustomerDetailsTestConstants.scala
test/assets/PPOBAddressTestConstants.scala
test/assets/ReturnPeriodTestConstants.scala
test/assets/ViewModelsTestConstants.scala
test/audit/models/ViewVatSubscriptionAuditModelSpec.scala
test/models/AgentUserSpec.scala
test/models/UserSpec.scala
test/models/YesNoSpec.scala
test/models/circumstanceInfo/CircumstanceDetailsSpec.scala
test/models/circumstanceInfo/CustomerDetailsSpec.scala
test/models/customerAddress/AddressLookupJsonBuilderSpec.scala
test/models/returnFrequency/ReturnPeriodSpec.scala

[BTAT-9964] Update test coverage for models

---

README.md

[BTAT-9972] Remove service manager profile from readme

---

conf/messages
conf/messages.cy

Updating change address title following WTU feedback

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
conf/application.conf

I had to keep the value in AppConfig due to the ALF JSON builder using the a11y statement URL
Please merge this first: https://github.com/hmrc/app-config-base/pull/6547

BTAT-10012 Updated link/config for a11y statement

---

.gitignore
app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/views/MainTemplate.scala.html
build.sbt
conf/application.conf
project/build.properties
project/plugins.sbt

[BTAT-10126] - Updated sbt and to use hmrcReportTechnicalIssueHelper

---

app/views/missingTrader/ConfirmBusinessAddressView.scala.html
build.sbt
test/controllers/missingTrader/ConfirmAddressControllerSpec.scala
test/views/missingTrader/ConfirmBusinessAddressViewSpec.scala

Also added missing unit test for form action URL

BTAT-10141 Added double click prevention to missing trader confirmation button

---

app/common/SessionKeys.scala
app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/controllers/CustomerCircumstanceDetailsController.scala
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/app.routes
conf/application.conf
conf/messages
conf/messages.cy
it/pages/CustomerCircumstancesDetailsControllerISpec.scala
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/controllers/CustomerCircumstanceDetailsControllerSpec.scala
test/mocks/MockAppConfig.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

App Config Base PR: https://github.com/hmrc/app-config-base/pull/6956/files

[BTAT-10352] - Update email nudge notification and link

---

conf/messages
conf/messages.cy
test/assets/CircumstanceDetailsTestConstants.scala
test/assets/messages/SignupBannerMessages.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[BTAT-10481] Updated MTD signup notification banner

---

conf/messages.cy

[BTAT-10524] Updated Welsh for MTD sign up banner

---

build.sbt
it/helpers/BaseIntegrationSpec.scala
project/plugins.sbt
test/controllers/missingTrader/ConfirmAddressControllerSpec.scala
test/utils/TestUtil.scala

[BTAT-10536] - Updated Bootstrap and play and also added auth token to IT tests

---

app/views/businessAddress/ChangeAddressConfirmationView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt
it/pages/BusinessAddressControllerISpec.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

AT PR: https://github.com/hmrc/change-vat-acceptance-tests/pull/249

BTAT-10690 update to latest play-frontend-hmrc

---

app/audit/AuditService.scala
app/config/ConfigKeys.scala
app/config/features/Features.scala
app/connectors/SubscriptionConnector.scala
app/models/circumstanceInfo/PendingChanges.scala
app/models/customerAddress/AddressLookupJsonBuilder.scala
app/models/returnFrequency/ReturnPeriod.scala
app/testOnly/controllers/FeatureSwitchController.scala
app/testOnly/forms/FeatureSwitchForm.scala
app/testOnly/models/FeatureSwitchModel.scala
app/testOnly/views/FeatureSwitchView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt
conf/application.conf
test/assets/CustomerAddressTestConstants.scala
test/models/customerAddress/AddressLookupJsonBuilderSpec.scala
test/models/returnFrequency/ReturnPeriodSpec.scala
test/utils/TestUtil.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

I removed a few things we weren't using, such as a couple of implicit Writes in models we weren't writing anywhere, and this brought the test coverage up

[BTAT-10770] Remove overseas change of PPOB feature switch

---

build.sbt
it/helpers/BaseIntegrationSpec.scala
it/helpers/SessionCookieBaker.scala
it/helpers/SessionCookieCrumbler.scala

[BTAT 10807] - Updated Bootstrap to 7.0.0

---

build.sbt

[BTAT-10857] Update bootstrap test dependency

---

build.sbt
conf/application.conf

[BTAT-10914] - Updated container id for tracking consent

---

README.md

[BTAT-11162] Update readme to refer to run.sh script

---

app/assets/stylesheets/application.scss
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
app/views/missingTrader/ConfirmBusinessAddressView.scala.html
test/views/missingTrader/ConfirmBusinessAddressViewSpec.scala

BTAT-11260 Updated manage-vat-subscription with TTP wording

---

app/assets/stylesheets/application.scss
app/views/missingTrader/ConfirmBusinessAddressView.scala.html
project/plugins.sbt

[BTAT-11260] Added new custom class for grey non-hint text

---

app/utils/ImplicitDateFormatter.scala
app/views/helpers/BackToAddressConfirmation.scala.html
build.sbt
test/models/returnFrequency/ReturnPeriodSpec.scala

[BTAT-11424] Address compilation warnings

---

build.sbt
conf/application.conf
project/plugins.sbt

BTAT-11505 Fixing VAT pdf link while design is being reviewed

---

app/views/MainTemplate.scala.html

[BTAT-11500] Removing beta phase banner

---

app/views/businessAddress/ChangeAddressView.scala.html
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
build.sbt

[BTAT-11588] Upgrading play-frontend-hmrc version

---

app/config/ConfigKeys.scala
app/config/FrontendAppConfig.scala
app/config/features/Features.scala
app/views/customerInfo/CustomerCircumstanceDetailsView.scala.html
conf/application.conf
conf/messages
conf/messages.cy
test/assets/messages/CustomerCircumstanceDetailsPageMessages.scala
test/mocks/MockAppConfig.scala
test/views/customerInfo/CustomerCircumstanceDetailsViewSpec.scala

[DL-13380] - webchat link added

---

app/views/MainTemplate.scala.html

[AssetsFix] fix assets location

---

app/views/businessName/ChangeBusinessNameView.scala.html
conf/messages
conf/messages.cy
test/assets/messages/ChangeBusinessNamePageMessages.scala

DL-15444: Fixed title and links opening in new tabs
